"""Excepciones: continuación"""
# Observa el código en el editor. ¿Qué pasará cuando lo ejecutes? Revísalo.

mylist=[]
x=mylist[0]
# Verás el siguiente mensaje en respuesta:

# Traceback (most recent call last):
# File "lst.py", line 2, in 
# x = list[0]
# IndexError: list index out of range
# salida

# Este es el IndexError (Error de Índice).

